// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_log.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConversationLog = `-- name: CreateConversationLog :exec
INSERT INTO conversation_log (
    run_id,
    message_id,
    method_id,
    llm_id,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateConversationLogParams struct {
	RunID     uuid.UUID
	MessageID uuid.UUID
	MethodID  uuid.NullUUID
	LlmID     uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) CreateConversationLog(ctx context.Context, arg CreateConversationLogParams) error {
	_, err := q.db.ExecContext(ctx, createConversationLog,
		arg.RunID,
		arg.MessageID,
		arg.MethodID,
		arg.LlmID,
		arg.CreatedAt,
	)
	return err
}

const getConversationLog = `-- name: GetConversationLog :many
SELECT
    cl.created_at,

    CASE
        WHEN cl.llm_id IS NOT NULL THEN l.model
        ELSE m.name
    END AS actor_name,

    CASE
        WHEN cl.llm_id IS NOT NULL THEN cl.llm_id
        ELSE cl.method_id
    END AS actor_id,

    CASE
        WHEN cl.llm_id IS NOT NULL THEN 'llm'
        ELSE 'method'
    END AS actor_type,

    msg.message

FROM conversation_log AS cl

JOIN message AS msg
    ON msg.id = cl.message_id

LEFT JOIN llm AS l
    ON l.id = cl.llm_id

LEFT JOIN method AS m
    ON m.id = cl.method_id

WHERE cl.run_id = $1

ORDER BY cl.created_at
`

type GetConversationLogRow struct {
	CreatedAt time.Time
	ActorName interface{}
	ActorID   interface{}
	ActorType string
	Message   string
}

func (q *Queries) GetConversationLog(ctx context.Context, runID uuid.UUID) ([]GetConversationLogRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationLog, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationLogRow
	for rows.Next() {
		var i GetConversationLogRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorID,
			&i.ActorType,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
