// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createLLM = `-- name: CreateLLM :one
INSERT INTO llm (id, model, hardware, config)
VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id
`

type CreateLLMParams struct {
	ID       uuid.UUID
	Model    string
	Hardware pqtype.NullRawMessage
	Config   json.RawMessage
}

func (q *Queries) CreateLLM(ctx context.Context, arg CreateLLMParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createLLM,
		arg.ID,
		arg.Model,
		arg.Hardware,
		arg.Config,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLLMs = `-- name: GetLLMs :many
SELECT id, model, hardware, config FROM llm
`

func (q *Queries) GetLLMs(ctx context.Context) ([]Llm, error) {
	rows, err := q.db.QueryContext(ctx, getLLMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Llm
	for rows.Next() {
		var i Llm
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Hardware,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
