// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearLogBefore = `-- name: ClearLogBefore :exec
DELETE FROM log
WHERE created_at < $1
`

func (q *Queries) ClearLogBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, clearLogBefore, createdAt)
	return err
}

const createLog = `-- name: CreateLog :exec
INSERT INTO log (id, type, message, database_key, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateLogParams struct {
	ID          uuid.UUID
	Type        string
	Message     string
	DatabaseKey string
	CreatedAt   time.Time
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.ExecContext(ctx, createLog,
		arg.ID,
		arg.Type,
		arg.Message,
		arg.DatabaseKey,
		arg.CreatedAt,
	)
	return err
}

const getLogs = `-- name: GetLogs :many
SELECT id, type, message, database_key, created_at FROM log
ORDER BY created_at
`

func (q *Queries) GetLogs(ctx context.Context) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Message,
			&i.DatabaseKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
