// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (id, message, hash)
    VALUES ($1, $2, $3)
    ON CONFLICT (hash)
        DO UPDATE SET message = EXCLUDED.message
RETURNING id
`

type CreateMessageParams struct {
	ID      uuid.UUID
	Message string
	Hash    []byte
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ID, arg.Message, arg.Hash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, message, hash FROM message
`

func (q *Queries) GetMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.Message, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
