// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (id, message)
VALUES (
    $1,
    $2
)
RETURNING id
`

type CreateMessageParams struct {
	ID      uuid.UUID
	Message string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ID, arg.Message)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, message FROM message
`

func (q *Queries) GetMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
