// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: method.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMethod = `-- name: CreateMethod :one
INSERT INTO method (id, name, source, config)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT unique_method
DO UPDATE SET
    name = EXCLUDED.name,
    source = EXCLUDED.source,
    config = EXCLUDED.config
RETURNING id
`

type CreateMethodParams struct {
	ID     uuid.UUID
	Name   string
	Source string
	Config json.RawMessage
}

func (q *Queries) CreateMethod(ctx context.Context, arg CreateMethodParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMethod,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Config,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMethods = `-- name: GetMethods :many
SELECT id, name, source, config FROM method
`

func (q *Queries) GetMethods(ctx context.Context) ([]Method, error) {
	rows, err := q.db.QueryContext(ctx, getMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Method
	for rows.Next() {
		var i Method
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
