// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: method_llm.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMethodLLM = `-- name: CreateMethodLLM :exec
INSERT INTO method_llm (method_id, llm_id)
VALUES (
    $1,
    $2
)
`

type CreateMethodLLMParams struct {
	MethodID uuid.UUID
	LlmID    uuid.UUID
}

func (q *Queries) CreateMethodLLM(ctx context.Context, arg CreateMethodLLMParams) error {
	_, err := q.db.ExecContext(ctx, createMethodLLM, arg.MethodID, arg.LlmID)
	return err
}

const getLLMsForMethod = `-- name: GetLLMsForMethod :many
SELECT llm.id, llm.model, llm.hash, llm.hardware, llm.config
FROM method_llm ml
JOIN llm
    ON llm.id = ml.llm_id
WHERE ml.method_id = $1
`

func (q *Queries) GetLLMsForMethod(ctx context.Context, methodID uuid.UUID) ([]Llm, error) {
	rows, err := q.db.QueryContext(ctx, getLLMsForMethod, methodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Llm
	for rows.Next() {
		var i Llm
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Hash,
			&i.Hardware,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
