// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ConversationLog struct {
	RunID     uuid.UUID
	MessageID uuid.UUID
	MethodID  uuid.UUID
	LlmID     uuid.UUID
	CreatedAt time.Time
}

type Experiment struct {
	ID        uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type ExperimentRun struct {
	ExperimentID uuid.UUID
	RunID        uuid.UUID
}

type Llm struct {
	ID       uuid.UUID
	Model    string
	Hardware pqtype.NullRawMessage
	Config   json.RawMessage
}

type Message struct {
	ID      uuid.UUID
	Message string
}

type Method struct {
	ID     uuid.UUID
	Name   string
	Source string
	Config json.RawMessage
}

type MethodLlm struct {
	MethodID uuid.UUID
	LlmID    uuid.UUID
}

type Problem struct {
	ID           uuid.UUID
	Name         string
	Prompt       string
	Evaluator    string
	Minimisation bool
	Config       pqtype.NullRawMessage
}

type Run struct {
	ID   uuid.UUID
	Seed int32
}

type RunDescriptor struct {
	RunID     uuid.UUID
	MethodID  uuid.UUID
	ProblemID uuid.UUID
}

type RunSolution struct {
	RunID      uuid.UUID
	SolutionID uuid.UUID
}

type Solution struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	Generation  sql.NullInt32
	Code        sql.NullString
	Metadata    pqtype.NullRawMessage
	Fitness     pqtype.NullRawMessage
}

type SolutionParentChild struct {
	ParentID uuid.UUID
	ChildID  uuid.UUID
}

type Tag struct {
	ID  uuid.UUID
	Tag string
}

type TagProblem struct {
	TagID     uuid.UUID
	ProblemID uuid.UUID
}
