// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent_child.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createParentChild = `-- name: CreateParentChild :exec
INSERT INTO solution_parent_child (parent_id, child_id)
VALUES (
    $1,
    $2
)
`

type CreateParentChildParams struct {
	ParentID uuid.UUID
	ChildID  uuid.UUID
}

func (q *Queries) CreateParentChild(ctx context.Context, arg CreateParentChildParams) error {
	_, err := q.db.ExecContext(ctx, createParentChild, arg.ParentID, arg.ChildID)
	return err
}

const getChildrenofSolution = `-- name: GetChildrenofSolution :many
SELECT solution.id, solution.name, solution.description, solution.generation, solution.code, solution.metadata, solution.fitness
FROM solution_parent_child pc
JOIN solution
    ON solution.id = pc.child_id
WHERE pc.parent_id = $1
`

func (q *Queries) GetChildrenofSolution(ctx context.Context, parentID uuid.UUID) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getChildrenofSolution, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Generation,
			&i.Code,
			&i.Metadata,
			&i.Fitness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentsofSolution = `-- name: GetParentsofSolution :many
SELECT solution.id, solution.name, solution.description, solution.generation, solution.code, solution.metadata, solution.fitness
FROM solution_parent_child pc
JOIN solution
    ON solution.id = pc.parent_id
WHERE pc.child_id = $1
`

func (q *Queries) GetParentsofSolution(ctx context.Context, childID uuid.UUID) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getParentsofSolution, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Generation,
			&i.Code,
			&i.Metadata,
			&i.Fitness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
