// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pre_test_cleanup.sql

package database

import (
	"context"
)

const clearExperiment = `-- name: ClearExperiment :exec
DELETE FROM experiment
`

func (q *Queries) ClearExperiment(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExperiment)
	return err
}

const clearLLM = `-- name: ClearLLM :exec
DELETE FROM llm
`

func (q *Queries) ClearLLM(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearLLM)
	return err
}

const clearMessage = `-- name: ClearMessage :exec
DELETE FROM message
`

func (q *Queries) ClearMessage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMessage)
	return err
}

const clearMethod = `-- name: ClearMethod :exec
DELETE FROM method
`

func (q *Queries) ClearMethod(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMethod)
	return err
}

const clearProblem = `-- name: ClearProblem :exec
DELETE FROM problem
`

func (q *Queries) ClearProblem(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearProblem)
	return err
}

const clearRun = `-- name: ClearRun :exec
DELETE FROM run
`

func (q *Queries) ClearRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRun)
	return err
}

const clearRunSolution = `-- name: ClearRunSolution :exec
DELETE FROM run_solution
`

func (q *Queries) ClearRunSolution(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRunSolution)
	return err
}

const clearSolution = `-- name: ClearSolution :exec
DELETE FROM solution
`

func (q *Queries) ClearSolution(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSolution)
	return err
}

const clearTag = `-- name: ClearTag :exec
DELETE FROM tag
`

func (q *Queries) ClearTag(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTag)
	return err
}

const clearTagProblem = `-- name: ClearTagProblem :exec
DELETE FROM tag_problem
`

func (q *Queries) ClearTagProblem(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTagProblem)
	return err
}
