// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pre_test_cleanup.sql

package database

import (
	"context"
)

const clearExperiment = `-- name: ClearExperiment :exec
DELETE FROM experiment
`

func (q *Queries) ClearExperiment(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExperiment)
	return err
}

const clearMessage = `-- name: ClearMessage :exec
DELETE FROM message
`

func (q *Queries) ClearMessage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMessage)
	return err
}

const clearProblem = `-- name: ClearProblem :exec
DELETE FROM problem
`

func (q *Queries) ClearProblem(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearProblem)
	return err
}

const clearRun = `-- name: ClearRun :exec
DELETE FROM run
`

func (q *Queries) ClearRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRun)
	return err
}

const clearTag = `-- name: ClearTag :exec
DELETE FROM tag
`

func (q *Queries) ClearTag(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTag)
	return err
}
