// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pre_test_cleanup.sql

package database

import (
	"context"
)

const clearConversationLog = `-- name: ClearConversationLog :exec
DELETE FROM conversation_log
`

func (q *Queries) ClearConversationLog(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearConversationLog)
	return err
}

const clearExperiment = `-- name: ClearExperiment :exec
DELETE FROM experiment
`

func (q *Queries) ClearExperiment(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExperiment)
	return err
}

const clearExperimentRun = `-- name: ClearExperimentRun :exec
DELETE FROM experiment_run
`

func (q *Queries) ClearExperimentRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearExperimentRun)
	return err
}

const clearLLM = `-- name: ClearLLM :exec
DELETE FROM llm
`

func (q *Queries) ClearLLM(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearLLM)
	return err
}

const clearMessage = `-- name: ClearMessage :exec
DELETE FROM message
`

func (q *Queries) ClearMessage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMessage)
	return err
}

const clearMethod = `-- name: ClearMethod :exec
DELETE FROM method
`

func (q *Queries) ClearMethod(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMethod)
	return err
}

const clearMethodLLM = `-- name: ClearMethodLLM :exec
DELETE FROM method_llm
`

func (q *Queries) ClearMethodLLM(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMethodLLM)
	return err
}

const clearParentChild = `-- name: ClearParentChild :exec
DELETE FROM solution_parent_child
`

func (q *Queries) ClearParentChild(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearParentChild)
	return err
}

const clearProblem = `-- name: ClearProblem :exec
DELETE FROM problem
`

func (q *Queries) ClearProblem(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearProblem)
	return err
}

const clearRun = `-- name: ClearRun :exec
DELETE FROM run
`

func (q *Queries) ClearRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRun)
	return err
}

const clearRunDescriptor = `-- name: ClearRunDescriptor :exec
DELETE FROM run_descriptor
`

func (q *Queries) ClearRunDescriptor(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRunDescriptor)
	return err
}

const clearRunSolution = `-- name: ClearRunSolution :exec
DELETE FROM run_solution
`

func (q *Queries) ClearRunSolution(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRunSolution)
	return err
}

const clearSolution = `-- name: ClearSolution :exec
DELETE FROM solution
`

func (q *Queries) ClearSolution(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSolution)
	return err
}

const clearTag = `-- name: ClearTag :exec
DELETE FROM tag
`

func (q *Queries) ClearTag(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTag)
	return err
}

const clearTagProblem = `-- name: ClearTagProblem :exec
DELETE FROM tag_problem
`

func (q *Queries) ClearTagProblem(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTagProblem)
	return err
}
