// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problem (id, name, prompt, evaluator, minimisation, config)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ON CONSTRAINT unique_problem
DO UPDATE SET
    name = EXCLUDED.name,
    prompt = EXCLUDED.prompt,
    evaluator = EXCLUDED.evaluator,
    minimisation = EXCLUDED.minimisation,
    config = EXCLUDED.config
RETURNING id
`

type CreateProblemParams struct {
	ID           uuid.UUID
	Name         string
	Prompt       string
	Evaluator    string
	Minimisation bool
	Config       pqtype.NullRawMessage
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ID,
		arg.Name,
		arg.Prompt,
		arg.Evaluator,
		arg.Minimisation,
		arg.Config,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProblems = `-- name: GetProblems :many
SELECT id, name, prompt, evaluator, minimisation, config FROM problem
`

func (q *Queries) GetProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.Evaluator,
			&i.Minimisation,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
