// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRun = `-- name: CreateRun :one
INSERT INTO run (id, name, seed)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateRunParams struct {
	ID   uuid.UUID
	Name string
	Seed int32
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.ID, arg.Name, arg.Seed)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRuns = `-- name: GetRuns :many
SELECT id, name, seed FROM run
`

func (q *Queries) GetRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, getRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(&i.ID, &i.Name, &i.Seed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
