// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_solution.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRunSolution = `-- name: CreateRunSolution :exec
INSERT INTO run_solution (run_id, solution_id)
VALUES (
    $1,
    $2
)
`

type CreateRunSolutionParams struct {
	RunID      uuid.UUID
	SolutionID uuid.UUID
}

func (q *Queries) CreateRunSolution(ctx context.Context, arg CreateRunSolutionParams) error {
	_, err := q.db.ExecContext(ctx, createRunSolution, arg.RunID, arg.SolutionID)
	return err
}

const getSolutionsForRun = `-- name: GetSolutionsForRun :many
SELECT solution.id, solution.name, solution.description, solution.generation, solution.code, solution.metadata, solution.fitness
FROM run_solution rs
JOIN solution
    ON solution.id = rs.solution_id
WHERE rs.run_id = $1
`

func (q *Queries) GetSolutionsForRun(ctx context.Context, runID uuid.UUID) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutionsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Generation,
			&i.Code,
			&i.Metadata,
			&i.Fitness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
