// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_descriptor.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRunDescriptor = `-- name: CreateRunDescriptor :exec
INSERT INTO run_descriptor (run_id, method_id, problem_id)
VALUES (
    $1,
    $2,
    $3)
`

type CreateRunDescriptorParams struct {
	RunID     uuid.UUID
	MethodID  uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) CreateRunDescriptor(ctx context.Context, arg CreateRunDescriptorParams) error {
	_, err := q.db.ExecContext(ctx, createRunDescriptor, arg.RunID, arg.MethodID, arg.ProblemID)
	return err
}

const getMethodAndProblemForRun = `-- name: GetMethodAndProblemForRun :many
SELECT
    p.id           AS problem_id,
    p.name         AS problem_name,
    p.prompt       AS problem_prompt,
    p.evaluator    AS problem_evaluator,
    p.minimisation AS problem_minimisation,
    p.config       AS problem_config,

    m.id           AS method_id,
    m.name         AS method_name,
    m.source       AS method_source,
    m.config       AS method_config
FROM run_descriptor rd
JOIN problem p
    ON p.id = rd.problem_id
JOIN method m
    ON m.id = rd.method_id
WHERE rd.problem_id = $1
`

type GetMethodAndProblemForRunRow struct {
	ProblemID           uuid.UUID
	ProblemName         string
	ProblemPrompt       string
	ProblemEvaluator    string
	ProblemMinimisation bool
	ProblemConfig       pqtype.NullRawMessage
	MethodID            uuid.UUID
	MethodName          string
	MethodSource        string
	MethodConfig        json.RawMessage
}

func (q *Queries) GetMethodAndProblemForRun(ctx context.Context, problemID uuid.UUID) ([]GetMethodAndProblemForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, getMethodAndProblemForRun, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMethodAndProblemForRunRow
	for rows.Next() {
		var i GetMethodAndProblemForRunRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.ProblemName,
			&i.ProblemPrompt,
			&i.ProblemEvaluator,
			&i.ProblemMinimisation,
			&i.ProblemConfig,
			&i.MethodID,
			&i.MethodName,
			&i.MethodSource,
			&i.MethodConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
