// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: solution.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSolution = `-- name: CreateSolution :one
INSERT INTO solution (id, name, description, generation, code, metadata, fitness)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id
`

type CreateSolutionParams struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	Generation  sql.NullInt32
	Code        sql.NullString
	Metadata    pqtype.NullRawMessage
	Fitness     pqtype.NullRawMessage
}

func (q *Queries) CreateSolution(ctx context.Context, arg CreateSolutionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSolution,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Generation,
		arg.Code,
		arg.Metadata,
		arg.Fitness,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSolutions = `-- name: GetSolutions :many
SELECT id, name, description, generation, code, metadata, fitness FROM solution
`

func (q *Queries) GetSolutions(ctx context.Context) ([]Solution, error) {
	rows, err := q.db.QueryContext(ctx, getSolutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solution
	for rows.Next() {
		var i Solution
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Generation,
			&i.Code,
			&i.Metadata,
			&i.Fitness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
