// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tag (id, tag)
VALUES (
    $1,
    $2
)
RETURNING id
`

type CreateTagParams struct {
	ID  uuid.UUID
	Tag string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.ID, arg.Tag)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTags = `-- name: GetTags :many
SELECT id, tag FROM tag
`

func (q *Queries) GetTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
