// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_problem.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const connectTagProblem = `-- name: ConnectTagProblem :exec
INSERT INTO tag_problem (tag_id, problem_id)
VALUES (
    $1,
    $2
)
`

type ConnectTagProblemParams struct {
	TagID     uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) ConnectTagProblem(ctx context.Context, arg ConnectTagProblemParams) error {
	_, err := q.db.ExecContext(ctx, connectTagProblem, arg.TagID, arg.ProblemID)
	return err
}

const getTagsforProblem = `-- name: GetTagsforProblem :many
SELECT tag.tag
FROM tag_problem tp
JOIN tag
    ON tag.id = tp.tag_id
WHERE tp.problem_id = $1
`

func (q *Queries) GetTagsforProblem(ctx context.Context, problemID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsforProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
