// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, name, password_hash, is_admin)
VALUES (
    $1,
    $2,
    $3,
    $4
)  RETURNING id
`

type CreateUserParams struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserNamed = `-- name: GetUserNamed :one
SELECT id, name, password_hash, default_visibility, is_admin FROM users
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetUserNamed(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserNamed, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.DefaultVisibility,
		&i.IsAdmin,
	)
	return i, err
}

const setDefaultVisibility = `-- name: SetDefaultVisibility :exec
UPDATE users
SET default_visibility = $2
WHERE id = $1
`

type SetDefaultVisibilityParams struct {
	ID                uuid.UUID
	DefaultVisibility bool
}

func (q *Queries) SetDefaultVisibility(ctx context.Context, arg SetDefaultVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultVisibility, arg.ID, arg.DefaultVisibility)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
